const item = [
  {
    id: 1,
    image: 'images/PRODUCT/f1.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 2,
    image: 'images/PRODUCT/f2 (1).jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 334,
  },
  {
    id: 3,
    image: 'images/PRODUCT/f3.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 86,
  },
  {
    id: 4,
    image: 'images/PRODUCT/f4.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 5,
    image: 'images/PRODUCT/f5.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 43,
  },
  {
    id: 6,
    image: 'images/PRODUCT/f6.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 7,
    image: 'images/PRODUCT/n1.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 8,
    image: 'images/PRODUCT/n2.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 9,
    image: 'images/PRODUCT/n3.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 10,
    image: 'images/PRODUCT/n4.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 11,
    image: 'images/PRODUCT/n5.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 12,
    image: 'images/PRODUCT/n6.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 13,
    image: 'images/PRODUCT/n7.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
  {
    id: 14,
    image: 'images/PRODUCT/n8.jpg',
    brandName: 'Adidas',
    productName: 'Cartoon T-Shirt',
    price: 73,
  },
]
